spring:
  security:
    user:
      name: user
      password: $2y$08$mz3KavH5mF5GYICDNl2qouDfAwZOjt.Wvqa0alddg0Mn1cUEgrjk2
  sql:
    init:
      mode: always
  application:
    name: ea-project
  datasource:
    url: jdbc:mysql://ea-project-db-server.mysql.database.azure.com:3306/eaproject?useSSL=true&requireSSL=true
#    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=CS544-202303-08;encrypt=true;trustServerCertificate=true;
#    username: CS544-202303-08
#    password: dc70d089-d5a2-4fb3-b3b9-1e237116fdb7

#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: karna
    password: ea@Project
    ssl-mode: require
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log


